Repository PennyPence/pennypence-drf-backend, pull requests merged in 2023-02, with the labels that each got.

#2 DRF serializers 생성 및 urls 연결
  assets/__init__.py
  assets/admin.py
  assets/apps.py
  assets/migrations/0001_initial.py
  assets/migrations/__init__.py
  assets/models.py
  assets/serializers.py
  assets/tests.py
  assets/urls.py
  assets/views.py
  back/settings.py
  back/urls.py
  requirements.txt
Labels: 💻 기능 구현

#17 feat: QnA 앱 생성 및 베이스코드 작성
  questions/__init__.py
  questions/admin.py
  questions/apps.py
  questions/migrations/__init__.py
  questions/models.py
  questions/serializers.py
  questions/tests.py
  questions/urls.py
  questions/views.py
  test.py
Labels: 💻 기능 구현

#19 refact: 코드 리팩토링
  questions/models.py
  questions/serializers.py
  questions/urls.py
  questions/views.py
Labels: 💩 수정

#21 fix: 전체 적인 부분 코드 수정
  back/settings.py
  back/urls.py
  questions/migrations/0001_initial.py
  questions/models.py
  questions/serializers.py
  questions/urls.py
  questions/views.py
Labels: 🔨개선사항

#24 Sector 주가 데이터 추가
  assets/1.crawling_tests.py
  assets/2.crawling.py
  assets/3.sector_price.py
  assets/serializers.py
  requirements.txt
Labels: 💻 기능 구현

#27 fix: like 코드 리팩토링
  back/settings.py
  back/urls.py
  communities/__init__.py
  communities/admin.py
  communities/apps.py
  communities/migrations/0001_initial.py
  communities/migrations/__init__.py
  communities/models.py
  communities/serializers.py
  communities/tests.py
  communities/urls.py
  communities/views.py
Labels: 💩 수정

#30 feat: 크롤링 코드 조건문 추가 #30
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_remove_user_username.py
  assets/2.crawling.py
  assets/3.sector_price.py
  assets/migrations/0001_initial.py
  assets/models.py
  assets/sector_percentage.py
  assets/urls.py
  assets/views.py
  삼성전자 반도체_20230217_16시06분29초.csv
Labels: 💻 기능 구현

#34 feat: 옥션 앱 베이스 코드 작성 및 communities 코드 약간 수정
  auction/__init__.py
  auction/admin.py
  auction/apps.py
  auction/migrations/__init__.py
  auction/models.py
  auction/serializers.py
  auction/tests.py
  auction/urls.py
  auction/views.py
  back/settings.py
  back/urls.py
  communities/models.py
  communities/serializers.py
  communities/urls.py
  communities/views.py
Labels: 💻 기능 구현

#40 News리스트 데이터저장 코드 추가
  assets/migrations/0001_initial.py
  assets/sector_percentage.py
  assets/serializers.py
  assets/urls.py
  assets/views.py
Labels: 💻 기능 구현

#41 섹터 DB저장 코드 수정 #41
  assets/sector_percentage.py
  assets/views.py
Labels: 💩 수정

#42 feat: News Detail 메서드와 url 코드 추가 #42
  assets/urls.py
  assets/views.py
Labels: 💻 기능 구현

#43 fix: auction 주석 풀고 진행중
  auction/migrations/0001_initial.py
  auction/models.py
  auction/serializers.py
  communities/migrations/0002_alter_comment_parent.py
Labels: 💩 수정

#51 feat: 거래소 앱 수정 완료.
  auction/models.py
  auction/views.py
  communities/serializers.py
  requirements.txt
Labels: 💩 수정

#52 refact: 뉴스 크롤링 코드 수정 #52
  accounts/migrations/0002_auto_20230219_1438.py
  assets/2.crawling.py
  assets/sector_percentage.py
  assets/views.py
  네이버_20230219_18시03분45초.csv
  반도체 섹터.csv
  삼성전자 반도체_20230217_16시06분29초.csv
  셀트리온_20230219_17시37분19초.csv
  신풍제약_20230219_17시42분24초.csv
  유한양행_20230219_17시40분23초.csv
Labels: 💩 수정

#53 docs: 크롤링 데이터 문서 수정 #53
  assets/2.crawling.py
  assets/sector_percentage.py
  z1. IT 섹터.xlsx
  z2. 게임 섹터.xlsx
  z3. 바이오 섹터.xlsx
  z4. 반도체 섹터.xlsx
  z5, 엔터 섹터.xlsx
  z6. 자동차 섹터.xlsx
  네이버_20230219_18시03분45초.csv
  반도체 섹터.csv
  셀트리온_20230219_17시37분19초.csv
  신풍제약_20230219_17시42분24초.csv
  유한양행_20230219_17시40분23초.csv
Labels: 💩 수정

#54 feat: settings.py 프론트랑 연결 부분 추가
  back/settings.py
Labels: 💩 수정

#60 docs : 자동차 섹터 뉴스 정리 #60
  z6. 자동차 섹터.xlsx
Labels: 💩 수정

#61 fix: settings 오류 해결
  back/settings.py
Labels: 🐛 버그

#62 fix: settings.py 변경, requirements dj-rest-auth 변경
  back/settings.py
  requirements.txt
Labels: 🐛 버그

#67 feat: 셋팅, accounts views(프론트로 수정)
  accounts/views.py
  back/settings.py
Labels: 💩 수정

#68 fix : auction migrations 파일 재생성되는 부분 수정
  auction/migrations/0002_alter_auctionitem_end_at.py
  auction/migrations/0003_alter_auctionitem_end_at.py
  auction/migrations/0004_alter_auctionitem_end_at.py
  auction/migrations/0005_alter_auctionitem_end_at.py
  auction/migrations/0006_alter_auctionitem_end_at.py
  auction/migrations/0007_alter_auctionitem_end_at.py
  auction/migrations/0008_alter_auctionitem_end_at.py
  auction/migrations/0009_alter_auctionitem_end_at.py
  auction/models.py
Labels: 🐛 버그

#70 feat: 대댓글 댓글 분리 기능 추가.
  communities/serializers.py
  communities/views.py
Labels: 💻 기능 구현

#75 feat: Items 시리얼라이저 추가, auction에 items 시리얼라이저 추가.
  auction/migrations/0010_alter_auctionitem_end_at.py
  auction/migrations/0011_alter_auctionitem_end_at.py
  auction/serializers.py
  items/serializers.py
  requirements.txt
Labels: 💩 수정

#83 feat: 매수 페이지 출력 및 매수 코드 작성 #82
  assets/serializers.py
  assets/urls.py
  assets/views.py
Labels: 💻 기능 구현

#87 feat: 매수 로직 작성 #86
  assets/models.py
  assets/views.py
Labels: 💻 기능 구현

#89 feat: 자동매도 후 랭킹갱신 코드 작성 #88
  assets/views.py
Labels: 💻 기능 구현
